name = "Circuits"
uuid = "d2a218f5-c9f8-4bfd-b3ab-fe354e20ba05"
authors = ["David Gustavsson <david.e.gustavsson@gmail.com> and contributors"]
version = "0.1.0"

[deps]
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
